# execfile(r'C:\qtlab-aalto\scripts\Qubit\TimeDomain\swap_batch\0dbm_swap\swap_with_high_pulse_30.py')
# execfile(r'C:\qtlab-aalto\scripts\Qubit\TimeDomain\swap_batch\0dbm_swap\swap_with_high_pulse_100.py')
#execfile(r'C:\qtlab-aalto\scripts\Qubit\TimeDomain\swap_batch\0dbm_swap\swap_with_high_pulse_200.py')
#execfile(r'C:\qtlab-aalto\scripts\Qubit\TimeDomain\swap_batch\0dbm_swap\swap_with_high_pulse_300.py')
#execfile(r'C:\qtlab-aalto\scripts\Qubit\TimeDomain\swap_batch\0dbm_swap\swap_with_high_pulse_400.py')
#execfile(r'C:\qtlab-aalto\scripts\Qubit\TimeDomain\swap_batch\0dbm_swap\swap_with_high_pulse_500.py')
#execfile(r'C:\qtlab-aalto\scripts\Qubit\TimeDomain\swap_batch\0dbm_swap\swap_with_high_pulse_600.py')
#execfile(r'C:\qtlab-aalto\scripts\Qubit\TimeDomain\swap_batch\0dbm_swap\swap_with_high_pulse_800.py')
#execfile(r'C:\qtlab-aalto\scripts\Qubit\TimeDomain\swap_batch\0dbm_swap\swap_with_high_pulse_1000.py')
execfile(r'C:\qtlab-aalto\scripts\Qubit\TimeDomain\swap_batch\0dbm_swap\swap_with_high_pulse_2000.py')
execfile(r'C:\qtlab-aalto\scripts\Qubit\TimeDomain\swap_batch\0dbm_swap\swap_with_high_pulse_3000.py')
execfile(r'C:\qtlab-aalto\scripts\Qubit\TimeDomain\swap_batch\0dbm_swap\swap_with_high_pulse_4000.py')
execfile(r'C:\qtlab-aalto\scripts\Qubit\TimeDomain\swap_batch\0dbm_swap\swap_with_high_pulse_5000.py')
